/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    Registers: () => import('#controllers/auth/registers_controller'),
  },
  NewAccount: () => import('#controllers/new_account_controller'),
  Session: () => import('#controllers/session_controller'),
  tweets: {
    Stores: () => import('#controllers/tweets/stores_controller'),
  },
}
