/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    Registers: () => import('#controllers/auth/registers_controller'),
    StoreControllers: () => import('#controllers/auth/store_controllers'),
    VerifyEmails: () => import('#controllers/auth/verify_emails_controller'),
  },
  Grok: () => import('#controllers/grok_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  PasswordResets: () => import('#controllers/password_resets_controller'),
  profiles: {
    Blocks: () => import('#controllers/profiles/blocks_controller'),
    Follow: () => import('#controllers/profiles/follow_controller'),
    FollowRequests: () => import('#controllers/profiles/follow_requests_controller'),
  },
  Session: () => import('#controllers/session_controller'),
  tweets: {
    Destroys: () => import('#controllers/tweets/destroys_controller'),
    Likes: () => import('#controllers/tweets/likes_controller'),
    Retweets: () => import('#controllers/tweets/retweets_controller'),
    Searches: () => import('#controllers/tweets/searches_controller'),
    Shows: () => import('#controllers/tweets/shows_controller'),
    Stores: () => import('#controllers/tweets/stores_controller'),
  },
}
