/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    Registers: () => import('#controllers/auth/registers_controller'),
    StoreControllers: () => import('#controllers/auth/store_controllers'),
    VerifyEmails: () => import('#controllers/auth/verify_emails_controller'),
  },
  NewAccount: () => import('#controllers/new_account_controller'),
  profiles: {
    Follow: () => import('#controllers/profiles/follow_controller'),
  },
  Session: () => import('#controllers/session_controller'),
  tweets: {
    Destroys: () => import('#controllers/tweets/destroys_controller'),
    Likes: () => import('#controllers/tweets/likes_controller'),
    Stores: () => import('#controllers/tweets/stores_controller'),
  },
  PasswordResets: () => import('#controllers/password_resets_controller'),
}
