/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class FollowSchema extends BaseModel {
  static $columns = ['id', 'followerId', 'followingId', 'createdAt'] as const
  $columns = FollowSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare followerId: number | null
  @column()
  declare followingId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}

export class LikeSchema extends BaseModel {
  static $columns = ['id', 'userId', 'tweetId', 'createdAt'] as const
  $columns = LikeSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number | null
  @column()
  declare tweetId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}

export class TweetSchema extends BaseModel {
  static $columns = ['id', 'userId', 'content', 'createdAt', 'updatedAt', 'parentId'] as const
  $columns = TweetSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number | null
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare parentId: number | null
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'fullName', 'email', 'password', 'createdAt', 'updatedAt', 'avatarUrl', 'coverUrl', 'bio', 'isEmailVerified'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare fullName: string | null
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare avatarUrl: string | null
  @column()
  declare coverUrl: string | null
  @column()
  declare bio: string | null
  @column()
  declare isEmailVerified: boolean
}
